import argparse
import pandas as pd
from pathlib import Path
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline


MODEL_NAME = "cardiffnlp/twitter-roberta-base-sentiment-latest"


def parse_args():
    parser = argparse.ArgumentParser(description="Add sentiment labels to synthetic reviews CSV.")
    parser.add_argument(
        "--input_csv",
        type=str,
        required=True,
        help="Path to CSV file generated by generate_reviews.py"
    )
    parser.add_argument(
        "--output_csv",
        type=str,
        default="",
        help="Optional output CSV path"
    )
    return parser.parse_args()


def main():
    args = parse_args()
    input_csv = Path(args.input_csv).resolve()

    if not input_csv.exists():
        raise FileNotFoundError(f"File not found: {input_csv}")

    print(f"Loading reviews from: {input_csv}")
    df = pd.read_csv(input_csv)

    if "review_text" not in df.columns:
        raise ValueError("CSV must include 'review_text' column.")

    print("Loading sentiment model...")
    sentiment_pipeline = pipeline(
        "sentiment-analysis",
        model=AutoModelForSequenceClassification.from_pretrained(MODEL_NAME),
        tokenizer=AutoTokenizer.from_pretrained(MODEL_NAME)
    )

    labels_5 = {
        "LABEL_0": "very_negative",
        "LABEL_1": "negative",
        "LABEL_2": "neutral",
        "LABEL_3": "positive",
        "LABEL_4": "very_positive"
    }

    sentiments = []
    scores = []

    print("Running sentiment analysis...")
    for text in df["review_text"].tolist():
        result = sentiment_pipeline(text)[0]
        label = labels_5.get(result["label"], "unknown")
        sentiments.append(label)
        scores.append(result["score"])

    df["sentiment_label"] = sentiments
    df["sentiment_score"] = scores

    if args.output_csv:
        output_csv = Path(args.output_csv).resolve()
    else:
        output_csv = input_csv.parent / f"{input_csv.stem}_with_sentiment.csv"

    df.to_csv(output_csv, index=False, encoding="utf-8")

    print(f"Done. Output saved to: {output_csv}")


if __name__ == "__main__":
    main()
